// Per-topic chapter (the long-form walk-through behind a topic's exercises),
// prerendered as static JSON and fetched by the /catalog modal on demand. Kept
// out of catalog.astro for the same reason as the exercise details: 17 chapters
// would otherwise load with the table.
import type { APIRoute } from 'astro';
import { TOPICS } from '../../data/catalog';

type MdModule = {
  frontmatter: Record<string, unknown>;
  // Astro 5 resolves compiled markdown asynchronously.
  compiledContent: () => Promise<string>;
};

// Generated by `go run ./web/gen` from each topic's README.
const CHAPTERS = Object.fromEntries(
  Object.entries(import.meta.glob('../../data/chapters/*.md', { eager: true })).map(
    ([path, mod]) => [path.split('/').pop()!.replace(/\.md$/, ''), mod as MdModule]
  )
);

export function getStaticPaths() {
  return Object.keys(TOPICS).map((topic) => ({ params: { topic } }));
}

export const GET: APIRoute = async ({ params }) => {
  const topic = params.topic!;
  const chapter = CHAPTERS[topic];
  return new Response(
    JSON.stringify({ topic, chapter: chapter ? await chapter.compiledContent() : null }),
    { headers: { 'Content-Type': 'application/json' } }
  );
};
